# coding: utf-8

"""
    리로스쿨 API

    리로스쿨 2.9 버전의 API  # noqa: E501

    OpenAPI spec version: 2.9.0
    Contact: develop@rirosoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.message_api import MessageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self):
        self.api = api.message_api.MessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_message_badge_get(self):
        """Test case for message_badge_get

        뱃지 가져오기  # noqa: E501
        """
        pass

    def test_message_message_delete(self):
        """Test case for message_message_delete

        메시지 삭제하기  # noqa: E501
        """
        pass

    def test_message_message_get(self):
        """Test case for message_message_get

        메시지 가져오기  # noqa: E501
        """
        pass

    def test_message_read_get(self):
        """Test case for message_read_get

        메시지 읽음 표시  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
