# coding: utf-8

"""
    리로스쿨 API

    리로스쿨 2.9 버전의 API  # noqa: E501

    OpenAPI spec version: 2.9.0
    Contact: develop@rirosoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.child import Child  # noqa: E501
from swagger_client.rest import ApiException


class TestChild(unittest.TestCase):
    """Child unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChild(self):
        """Test Child"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.child.Child()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
